# Check that there is correct spelling in all files
name: Check spelling

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 3 * *"

jobs:
  check_spelling:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Remove folders that should not be spellchecked
      - run: rm -rf reflections

      - uses: igsekor/pyspelling-any@v0.0.2
