# Build and inspect the Python package
name: Check package

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 3 * *"

jobs:
  check-package:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@master

      - name: Install package requirements
        run: pip install -r requirements.txt

      - name: Install the package from the local code
        run: python3 -m pip install .

      - name: Run the code
        run: python3 benchmark.py
